stages:
  - cache
  - build
  - test
  - package
# - deploy

image: maven:3-jdk-8

variables:
  PRODUCTION_DOMAIN: http://localhost:8080/


before_script:
  - export JAVA_HOME="/usr/lib/jvm/jre-1.8.0-openjdk"
  - export MAVEN_USER_HOME=`pwd`/.maven
  - chmod +x mvnw
  - ./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-npm -DnodeVersion=v10.13.0 -DnpmVersion=6.4.1 -Dmaven.repo.local=$MAVEN_USER_HOME
  - ./mvnw com.github.eirslett:frontend-maven-plugin:npm -Dmaven.repo.local=$MAVEN_USER_HOME

update cache:
  stage: cache
  cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        - target/
      policy: push
  except:
    - schedules
  before_script:
    - echo "this job is going to update cache files and folders"

maven-compile:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
        - target/classes/
        - target/generated-sources/
  except:
    - schedules
  before_script:
    - echo "this job is going to build project"

maven-test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - ./mvnw test -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/test-results
  except:
    - schedules
  before_script:
    - echo "this job is going to test project"

maven-package:
  stage: package
  only:
    - master
    - merge_requests
  script:
    - ./mvnw verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/*.jar
  except:
    - schedules
  before_script:
    - echo "this job is going to package project"