stages:
  - package
  - deploy

image: maven:3-jdk-8


variables:
  PRODUCTION_DOMAIN: http://localhost:8040/
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - ./.m2/repository
  policy: pull

before_script:
  - export JAVA_HOME="/usr/lib/jvm/jre-1.8.0-openjdk"
  - export MAVEN_USER_HOME=`pwd`/.maven
  - chmod +x mvnw
  - ./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-npm -DnodeVersion=v10.13.0 -DnpmVersion=6.4.1 -Dmaven.repo.local=$MAVEN_USER_HOME
  - ./mvnw com.github.eirslett:frontend-maven-plugin:npm -Dmaven.repo.local=$MAVEN_USER_HOME

maven-compile:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
        - target/classes/
        - target/generated-sources/
  except:
    - schedules
  before_script:
    - echo "this job is going to build project"

maven-test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - ./mvnw test -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/*.jar
  except:
    - schedules
  before_script:
    - echo "this job is going to test project"

maven-package:
  stage: package
  only:
    - master
    - merge_requests
  script:
    - ./mvnw verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/*.jar
  except:
    - schedules
  before_script:
    - echo "this job is going to package project"

docker-push:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    REGISTRY_URL: https://registry.hub.docker.com
    DOCKER_REPO: springboot
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
    APPLICATION_NAME: springbootapplication
  dependencies:
    - maven-package
  before_script:
    - docker info
    - cp target/*.jar src/main/docker
  script:
   # - docker build -f src/main/docker/Dockerfile -t $IMAGE_TAG src/main/docker/ --rm=false
    - docker build -f src/main/docker/Dockerfile -t src/main/docker --rm=false
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
   # - docker push registry.hub.docker.com/repository/docker/devopsbatch17/springboot
    - docker push $REGISTRY_URL/$DOCKER_REPO:$IMAGE_TAG